const { initializeApp } = require("firebase-admin/app");
const { getFirestore, FieldValue, Timestamp } = require("firebase-admin/firestore");
const { defineSecret } = require("firebase-functions/params");
const { onDocumentCreated, onDocumentUpdated } = require("firebase-functions/v2/firestore");
const { onSchedule } = require("firebase-functions/v2/scheduler");
const { logger } = require("firebase-functions");

initializeApp();

const db = getFirestore();
const resendApiKey = defineSecret("RESEND_API_KEY");
const ADMIN_EMAIL = "admin@brightlearnersacademy.net";
const PORTAL_URL = "https://staff.brightlearnersacademy.net";
const FROM_EMAIL = "Bright Learners Staff Portal <notifications@notifications.brightlearnersacademy.net>";
const academyNames = ["Sundance", "Midnapore", "Sylvan Lake", "Millwoods", "Willowgrove"];
const directorEmails = {
  Sundance: "sundance@brightlearnersacademy.net",
  Midnapore: "midnapore@brightlearnersacademy.net",
  "Sylvan Lake": "sylvandaycare@gmail.com",
  Millwoods: "millwoods@brightlearnersacademy.net",
  Willowgrove: "willowgrove@brightlearnersacademy.net",
};

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function dateLabel(value) {
  const date = value?.toDate?.() || (value instanceof Date ? value : new Date(value));
  return Number.isNaN(date.getTime())
    ? "Not recorded"
    : new Intl.DateTimeFormat("en-CA", {
        dateStyle: "long",
        timeStyle: "short",
        timeZone: "America/Regina",
      }).format(date);
}

function dateOnly(value, timeZone = "America/Regina") {
  return new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    timeZone,
  }).format(value);
}

function addDays(date, days) {
  const next = new Date(date);
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

function dayDifference(today, due) {
  const start = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
  const end = Date.UTC(due.getUTCFullYear(), due.getUTCMonth(), due.getUTCDate());
  return Math.round((end - start) / 86400000);
}

function portalLink(path = "") {
  return `${PORTAL_URL}${path}`;
}

function emailShell({ preheader, heading, body, buttonLabel, buttonUrl, footer }) {
  return `<!doctype html>
  <html><body style="margin:0;background:#f5f7f9;color:#17345b;font-family:Arial,sans-serif">
    <div style="display:none;max-height:0;overflow:hidden">${escapeHtml(preheader)}</div>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f7f9;padding:28px 12px">
      <tr><td align="center">
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#fff;border:1px solid #dce3e9;border-radius:20px;overflow:hidden">
          <tr><td style="height:10px;background:#f6cf73"></td></tr>
          <tr><td style="padding:32px">
            <div style="font-size:13px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;color:#68827f">Bright Learners Academy</div>
            <h1 style="margin:12px 0 18px;font-size:30px;line-height:1.2;color:#17345b">${escapeHtml(heading)}</h1>
            <div style="font-size:16px;line-height:1.65;color:#53657c">${body}</div>
            ${buttonLabel ? `<p style="margin:28px 0 8px"><a href="${escapeHtml(buttonUrl)}" style="display:inline-block;padding:14px 20px;border-radius:10px;background:#17345b;color:#fff;text-decoration:none;font-weight:800">${escapeHtml(buttonLabel)}</a></p>` : ""}
          </td></tr>
          <tr><td style="padding:20px 32px;background:#f7faf9;color:#748296;font-size:12px;line-height:1.5">${escapeHtml(footer || "This automated message was generated by the Bright Learners staff portal.")}</td></tr>
        </table>
      </td></tr>
    </table>
  </body></html>`;
}

async function sendEmail({ idempotencyKey, type, to, cc = [], subject, html, metadata = {} }) {
  const logRef = db.collection("notificationDeliveries").doc(idempotencyKey);
  const existing = await logRef.get();
  if (existing.exists && existing.data().status === "sent") return existing.data();

  await logRef.set({
    type,
    to,
    cc,
    subject,
    metadata,
    status: "sending",
    attemptedAt: FieldValue.serverTimestamp(),
    createdAt: existing.exists ? existing.data().createdAt : FieldValue.serverTimestamp(),
  }, { merge: true });

  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendApiKey.value()}`,
        "Content-Type": "application/json",
        "Idempotency-Key": idempotencyKey,
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: Array.isArray(to) ? to : [to],
        cc,
        reply_to: ADMIN_EMAIL,
        subject,
        html,
      }),
    });
    const result = await response.json();
    if (!response.ok) throw new Error(result?.message || `Resend returned ${response.status}`);
    await logRef.set({
      status: "sent",
      provider: "resend",
      providerMessageId: result.id,
      sentAt: FieldValue.serverTimestamp(),
      lastError: FieldValue.delete(),
    }, { merge: true });
    return { status: "sent", providerMessageId: result.id };
  } catch (error) {
    await logRef.set({
      status: "failed",
      failedAt: FieldValue.serverTimestamp(),
      lastError: String(error?.message || error),
    }, { merge: true });
    throw error;
  }
}

exports.sendQueuedNotification = onDocumentCreated({
  document: "notificationQueue/{notificationId}",
  region: "us-east4",
  secrets: [resendApiKey],
  retry: true,
}, async (event) => {
  const data = event.data?.data();
  if (!data || data.status === "sent") return;
  const notificationId = event.params.notificationId;
  if (data.type !== "staff-signup") return;

  const html = emailShell({
    preheader: `${data.staffName} created a Bright Learners staff account.`,
    heading: "New staff account created",
    body: `<p><strong>${escapeHtml(data.staffName)}</strong> created a staff profile.</p>
      <p><strong>Email:</strong> ${escapeHtml(data.staffEmail)}<br>
      <strong>Location:</strong> ${escapeHtml(data.location)}<br>
      <strong>Role:</strong> ${escapeHtml(data.role)}<br>
      <strong>Province:</strong> ${escapeHtml(data.province)}</p>`,
    buttonLabel: "Review staff account",
    buttonUrl: portalLink(),
  });
  const result = await sendEmail({
    idempotencyKey: `queue-${notificationId}`,
    type: "staff-signup",
    to: ADMIN_EMAIL,
    subject: `New staff account: ${data.staffName} — ${data.location}`,
    html,
    metadata: { actorId: data.actorId, location: data.location },
  });
  await event.data.ref.set({
    status: result.status,
    providerMessageId: result.providerMessageId || null,
    attemptedAt: FieldValue.serverTimestamp(),
    sentAt: result.status === "sent" ? FieldValue.serverTimestamp() : null,
  }, { merge: true });
});

exports.sendCertificateCompletion = onDocumentCreated({
  document: "certificates/{certificateId}",
  region: "us-east4",
  secrets: [resendApiKey],
  retry: true,
}, async (event) => {
  const data = event.data?.data();
  if (!data) return;
  const checklist = Array.isArray(data.moduleChecklist)
    ? `<ol>${data.moduleChecklist.map((item) => `<li>${escapeHtml(item.title)} — Passed</li>`).join("")}</ol>`
    : "";
  const html = emailShell({
    preheader: `${data.employeeName} completed Bright Learners orientation.`,
    heading: "Employee orientation completed",
    body: `<p><strong>${escapeHtml(data.employeeName)}</strong> completed all required orientation modules with the required 100% score.</p>
      <p><strong>Location:</strong> ${escapeHtml(data.location)}<br>
      <strong>Province:</strong> ${escapeHtml(data.province)}<br>
      <strong>Completed:</strong> ${escapeHtml(dateLabel(data.issuedAt))}<br>
      <strong>Renewal due:</strong> ${escapeHtml(dateLabel(data.expiresAt))}</p>${checklist}
      <p>The signed certificate is stored in the Administration Console under Certificates.</p>`,
    buttonLabel: "View certificate",
    buttonUrl: portalLink(),
  });
  const result = await sendEmail({
    idempotencyKey: `certificate-${event.params.certificateId}`,
    type: "orientation-completed",
    to: ADMIN_EMAIL,
    subject: `Orientation completed: ${data.employeeName} — ${data.location}`,
    html,
    metadata: { certificateId: event.params.certificateId, userId: data.userId, location: data.location },
  });
  await event.data.ref.set({
    notificationStatus: result.status,
    providerMessageId: result.providerMessageId || null,
    notificationSentAt: FieldValue.serverTimestamp(),
  }, { merge: true });
});

exports.sendInspectionCompletion = onDocumentUpdated({
  document: "inspections/{inspectionId}",
  region: "us-east4",
  secrets: [resendApiKey],
  retry: true,
}, async (event) => {
  const before = event.data?.before.data();
  const after = event.data?.after.data();
  if (!after || before?.status === "completed" || after.status !== "completed") return;
  const responses = Object.values(after.responses || {});
  const failed = responses.filter((item) => item?.result === "fail").length;
  const notApplicable = responses.filter((item) => item?.result === "na").length;
  const html = emailShell({
    preheader: `${after.directorName} submitted the ${after.location} monthly inspection.`,
    heading: "Monthly inspection submitted",
    body: `<p><strong>${escapeHtml(after.directorName)}</strong> completed and signed the monthly facility inspection.</p>
      <p><strong>Location:</strong> ${escapeHtml(after.location)}<br>
      <strong>Completed:</strong> ${escapeHtml(dateLabel(after.completedAt))}<br>
      <strong>Checklist responses:</strong> ${escapeHtml(after.answeredCount || responses.length)}<br>
      <strong>Failed items:</strong> ${failed}<br>
      <strong>N/A items:</strong> ${notApplicable}</p>
      <p>The signed report, explanations, corrective actions and photographs are available in the Administration Console.</p>`,
    buttonLabel: "View inspection report",
    buttonUrl: portalLink(),
  });
  const result = await sendEmail({
    idempotencyKey: `inspection-${event.params.inspectionId}`,
    type: "inspection-completed",
    to: ADMIN_EMAIL,
    subject: `Inspection submitted: ${after.location} — ${after.directorName}`,
    html,
    metadata: { inspectionId: event.params.inspectionId, location: after.location, directorId: after.directorId },
  });
  await event.data.after.ref.set({
    notificationStatus: result.status,
    providerMessageId: result.providerMessageId || null,
    notificationSentAt: FieldValue.serverTimestamp(),
  }, { merge: true });
});

async function loadSchedule() {
  const snapshot = await db.collection("complianceSchedules").doc("default").get();
  return {
    inspectionDueDay: 15,
    renewalReminderDays: 30,
    ...(snapshot.exists ? snapshot.data() : {}),
  };
}

function monthlyDueDate(now, dueDay) {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), Math.min(28, Math.max(1, dueDay)), 18));
}

async function inspectionCompletedForMonth(location, due) {
  const snapshot = await db.collection("inspections")
    .where("location", "==", location)
    .get();
  return snapshot.docs.some((item) => {
    const data = item.data();
    const completed = data.completedAt?.toDate?.();
    return data.status === "completed"
      && completed
      && completed.getUTCFullYear() === due.getUTCFullYear()
      && completed.getUTCMonth() === due.getUTCMonth();
  });
}

async function sendInspectionReminders(now, schedule) {
  const due = monthlyDueDate(now, schedule.inspectionDueDay);
  const days = dayDifference(now, due);
  if (![7, 3, 0].includes(days) && days >= 0) return;

  await Promise.all(academyNames.map(async (location) => {
    if (await inspectionCompletedForMonth(location, due)) return;
    const directorEmail = directorEmails[location];
    if (!directorEmail) return;
    const overdueDays = Math.max(0, -days);
    const type = days === 7 ? "inspection-reminder-7" : days === 3 ? "inspection-reminder-3" : days === 0 ? "inspection-due" : "inspection-overdue";
    const timing = days > 0 ? `due in ${days} days` : days === 0 ? "due today" : `${overdueDays} day${overdueDays === 1 ? "" : "s"} overdue`;
    const html = emailShell({
      preheader: `${location}'s monthly inspection is ${timing}.`,
      heading: days < 0 ? "Monthly inspection is overdue" : "Monthly inspection reminder",
      body: `<p>The <strong>${escapeHtml(location)}</strong> monthly facility inspection is <strong>${escapeHtml(timing)}</strong>.</p>
        <p><strong>Due date:</strong> ${escapeHtml(dateLabel(due))}</p>
        <p>Open the Director Inspection portal to start or resume the checklist. The admin is copied on this reminder.</p>`,
      buttonLabel: "Open inspection portal",
      buttonUrl: portalLink(),
    });
    await sendEmail({
      idempotencyKey: `${type}-${dateOnly(due)}-${location.toLowerCase().replaceAll(" ", "-")}`,
      type,
      to: directorEmail,
      cc: [ADMIN_EMAIL],
      subject: `${days < 0 ? "Overdue" : "Reminder"}: ${location} monthly inspection ${timing}`,
      html,
      metadata: { location, dueDate: dateOnly(due), daysFromDue: days },
    });
  }));
}

async function sendCourseOverdueDigest(now) {
  const [progressSnapshot, usersSnapshot] = await Promise.all([
    db.collection("progress").where("dueAt", "<", Timestamp.fromDate(now)).get(),
    db.collection("users").where("status", "==", "active").get(),
  ]);
  const users = new Map(usersSnapshot.docs.map((item) => [item.id, item.data()]));
  const overdue = progressSnapshot.docs.flatMap((item) => {
    const data = item.data();
    if ((data.completedModules || []).length >= 8) return [];
    const user = users.get(data.userId);
    if (!user) return [];
    const due = data.dueAt?.toDate?.();
    return [{
      name: user.displayName || user.email,
      location: user.location,
      due,
      days: due ? Math.max(1, -dayDifference(now, due)) : 0,
    }];
  });
  if (!overdue.length) return;
  const rows = overdue
    .sort((a, b) => a.location.localeCompare(b.location) || a.name.localeCompare(b.name))
    .map((item) => `<tr><td style="padding:8px;border-bottom:1px solid #e4e9ed">${escapeHtml(item.name)}</td><td style="padding:8px;border-bottom:1px solid #e4e9ed">${escapeHtml(item.location)}</td><td style="padding:8px;border-bottom:1px solid #e4e9ed">${escapeHtml(dateLabel(item.due))}</td><td style="padding:8px;border-bottom:1px solid #e4e9ed">${item.days}</td></tr>`)
    .join("");
  const html = emailShell({
    preheader: `${overdue.length} employee orientation assignment(s) are overdue.`,
    heading: "Overdue employee orientation digest",
    body: `<p>${overdue.length} active employee orientation assignment${overdue.length === 1 ? " is" : "s are"} overdue.</p>
      <table width="100%" cellspacing="0" cellpadding="0"><thead><tr><th align="left">Employee</th><th align="left">Location</th><th align="left">Due</th><th align="left">Days</th></tr></thead><tbody>${rows}</tbody></table>`,
    buttonLabel: "Review staff progress",
    buttonUrl: portalLink(),
  });
  await sendEmail({
    idempotencyKey: `course-overdue-digest-${dateOnly(now)}`,
    type: "course-overdue-digest",
    to: ADMIN_EMAIL,
    subject: `Overdue orientation digest — ${overdue.length} assignment${overdue.length === 1 ? "" : "s"}`,
    html,
    metadata: { count: overdue.length, reportDate: dateOnly(now) },
  });
}

async function sendRenewalDigest(now, reminderDays) {
  const cutoff = Timestamp.fromDate(addDays(now, reminderDays));
  const snapshot = await db.collection("certificates").where("expiresAt", "<=", cutoff).get();
  const records = snapshot.docs.map((item) => ({ id: item.id, ...item.data() }))
    .filter((item) => item.expiresAt?.toDate?.());
  if (!records.length) return;
  const rows = records.map((item) => {
    const expiry = item.expiresAt.toDate();
    const days = dayDifference(now, expiry);
    return `<tr><td style="padding:8px;border-bottom:1px solid #e4e9ed">${escapeHtml(item.employeeName)}</td><td style="padding:8px;border-bottom:1px solid #e4e9ed">${escapeHtml(item.location)}</td><td style="padding:8px;border-bottom:1px solid #e4e9ed">${escapeHtml(dateLabel(expiry))}</td><td style="padding:8px;border-bottom:1px solid #e4e9ed">${days < 0 ? `${Math.abs(days)} overdue` : `${days} remaining`}</td></tr>`;
  }).join("");
  const html = emailShell({
    preheader: `${records.length} certificate renewal(s) need attention.`,
    heading: "Certificate renewal digest",
    body: `<p>The following Bright Learners orientation certificates are expired or approaching renewal.</p>
      <table width="100%" cellspacing="0" cellpadding="0"><thead><tr><th align="left">Employee</th><th align="left">Location</th><th align="left">Expiry</th><th align="left">Status</th></tr></thead><tbody>${rows}</tbody></table>`,
    buttonLabel: "Open certificate library",
    buttonUrl: portalLink(),
  });
  await sendEmail({
    idempotencyKey: `renewal-digest-${dateOnly(now)}`,
    type: "certificate-renewal-digest",
    to: ADMIN_EMAIL,
    subject: `Certificate renewal digest — ${records.length} record${records.length === 1 ? "" : "s"}`,
    html,
    metadata: { count: records.length, reportDate: dateOnly(now) },
  });
}

exports.runDailyComplianceEmails = onSchedule({
  schedule: "0 8 * * *",
  timeZone: "America/Regina",
  region: "us-east4",
  secrets: [resendApiKey],
  retryCount: 2,
}, async () => {
  const now = new Date();
  const schedule = await loadSchedule();
  const tasks = [
    sendInspectionReminders(now, schedule),
    sendCourseOverdueDigest(now),
    sendRenewalDigest(now, schedule.renewalReminderDays),
  ];
  const results = await Promise.allSettled(tasks);
  results.forEach((result, index) => {
    if (result.status === "rejected") logger.error("Scheduled email task failed", { index, error: result.reason });
  });
});
