export type InspectionSection = {
  id: string;
  title: string;
  items: Array<{ id: string; text: string }>;
};

const items = (section: string, values: string[]) =>
  values.map((text, index) => ({ id: `${section}-${index + 1}`, text }));

export const monthlyInspectionSections: InspectionSection[] = [
  {
    id: "licensing",
    title: "Licensing",
    items: items("lic", [
      "Emergency backpacks include first-aid kits, children's portable records, staff emergency numbers, gloves, masks and tissues.",
      "Educator certifications are current and tracked in staff files.",
      "Materials and books are accessible to all children in the program.",
      "Staff-to-child ratios comply with the requirements for each age group.",
      "Radios are charged and used in classrooms.",
      "Incident reports are completed properly with no required fields left blank.",
      "Medication forms include parent signatures, room posting where required, instructions and attached medication forms.",
      "Evacuation routes, muster points and the emergency shelter plan are posted.",
      "Entrances and exits are clear.",
      "Enrollment forms and emergency portable records are complete.",
      "Whiteboards and portable attendance records match.",
      "TimeSavr sign-in and sign-out records are complete.",
      "The program plan is accessible in every classroom.",
      "Emergency numbers are posted in every room.",
      "Emergency medications are in the appropriate emergency backpacks.",
      "The monthly fire drill has been completed and recorded.",
      "Information boards include parent newsletters, licensing information, fire-drill logs and upcoming events.",
      "Children's belongings are labelled.",
      "Headcounts are completed consistently throughout the program.",
      "All required licences are current and posted or available.",
    ]),
  },
  {
    id: "health-safety",
    title: "Health & Safety",
    items: items("hs", [
      "Diapering procedures are posted.",
      "The daily transition checklist is completed and posted to the approved staff channel.",
      "Handwashing procedures are posted.",
      "The daily health check is completed and posted to the approved staff channel.",
      "All required checklists have been reviewed for accuracy and missing information.",
      "Field-trip, walk and sunscreen forms are current and included in emergency packs where required.",
      "Daily and weekly cleaning checklists are completed in the approved system.",
      "Chemicals are inaccessible to children.",
      "Cabinets within children's reach are locked when they contain hazardous items.",
      "Children using bottles are held or seated safely and are not lying down while drinking.",
      "Outdoor vests, backpacks and radios are prepared before the group goes outside.",
      "Required First Aid and CPR training is current.",
      "Broken toys and furnishings are removed from use.",
      "Emergency medical plans are posted or immediately available in every applicable classroom.",
      "Medication documentation is complete and expiry dates have been checked.",
      "Sunscreen permission is documented where required.",
    ]),
  },
  {
    id: "public-health",
    title: "Public Health & Infection Prevention",
    items: items("ph", [
      "Handwashing occurs on arrival, before and after eating, and after toileting or diapering.",
      "Bleach or sanitizing bottles are labelled with correct instructions and solution strength is verified where required.",
      "The correct separate solution strengths are used for diapering surfaces and food-contact tables where required.",
      "Required food heating temperatures are posted and available onsite.",
      "Cleaning schedules are posted, current and accurate.",
      "Fridge and freezer temperature checks are completed and recorded.",
      "Sleep cots or beds are spaced according to the applicable health requirement and centre procedure.",
      "Tables are cleaned and sanitized before and after eating using the approved procedure.",
      "Blood-spill and vomit cleanup kits are stocked and accessible to staff.",
      "Required food-safety training is current.",
      "Gloves are changed after every diaper change and handwashing is completed.",
      "The current outbreak or public-health contact number is posted or immediately available.",
      "A designated supervised illness-separation area is identified.",
      "Illness logs are completed and kept in the approved location.",
      "Sanitizer strength is checked and documented at the required frequency.",
      "Weekly classroom toy cleaning is completed and recorded.",
    ]),
  },
  {
    id: "curriculum",
    title: "Curriculum & Planning",
    items: items("cur", [
      "Educator planning schedules are posted in classrooms.",
      "Play-topic boards and guiding questions are updated weekly.",
      "Portfolio content is added weekly.",
      "Weekly planning is posted in each classroom.",
      "A meaningful provocation is visible in the classroom.",
      "Collaborative planning time is provided for all rooms each week.",
      "Required Lillio updates are completed daily.",
      "Living walls are current and make children's learning visible.",
      "Activities are meaningful and based on children's interests.",
      "Toys and materials are organized and labelled.",
      "The classroom setup supports children's developmental needs.",
      "Learning stories and pedagogical documentation are posted.",
      "Activities support holistic growth and individual needs.",
      "The environment provides opportunities for exploration, curiosity and play.",
      "Displayed classroom content is presented professionally.",
    ]),
  },
  {
    id: "transitions",
    title: "Transitions",
    items: items("tr", [
      "Children receive adequate warning before an activity ends.",
      "Visual schedules, timers or visual cards are used for children who need them.",
      "Headcounts are completed throughout transitions.",
      "Small groups are used when practical to reduce waiting time.",
      "Songs or games are used appropriately to support calm transitions.",
      "Educators communicate clearly when children move between rooms.",
      "Children are accounted for before entering or leaving a classroom.",
      "Educators announce transitions in advance.",
      "Children are signed out of their primary classroom when moving to another classroom.",
    ]),
  },
  {
    id: "supervision",
    title: "Supervision",
    items: items("sup", [
      "Materials are organized to prevent avoidable injuries.",
      "Headcount and sign-in procedures are completed consistently.",
      "Staff remain within arm's reach during higher-risk play when required.",
      "Staff positions provide visibility and avoid blind spots.",
      "Required ratios are maintained at all times.",
      "Active supervision is evident during peak transition periods.",
      "Staff communicate during transitions.",
      "Room safety checks confirm that hazards are not accessible to children.",
      "Personal cellphones are not used while supervising children.",
      "Supervision responsibility is handed over clearly before an educator leaves the room.",
    ]),
  },
];
